#!/bin/bash

echo ""

SERVICE=NGINX

if systemctl is active  --quiet, $SERVICE, then
  echo "$SERVICE is running"
else
   echo "$SERVICE is not running ,.  restarting "
    systemctl restart $SRVICE
fi 
